import type { InferGetServerSidePropsType, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Avatar } from "../components/Avatar";
import { Card } from "../components/Card";
import { HomeLayout } from "../components/HomeLayout";
import { ShareCard } from "../components/ShareCard";
import styles from "../styles/Home.module.css";
import { PostData } from "../types";
import { theme } from "../styles/theme";
import { ThumbsUp, MessageSquare, Share, Send } from "react-feather";
import { Button } from "../components/Button";

export const getServerSideProps = async () => {
  // Fetch data from external API
  const res = await fetch(`http://localhost:3000/api/posts`);
  const data: PostData[] = await res.json();

  // Pass data to the page via props
  return { props: { data } };
};

type Props = InferGetServerSidePropsType<typeof getServerSideProps>;

const Home: NextPage<Props> = ({ data }) => {
  return (
    <HomeLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        css={(theme) => ({
          justifyContent: "center",
        })}
      >
        <ShareCard />
        {data.map((post) => (
          <Card key={post.id} padding="lg">
            <Card.Header postdata={post}></Card.Header>
            <Card.Content>
              <p
                css={{
                  fontSize: "14px",
                  lineHeight: "150%",
                  color: theme.colors.blackA[8],
                  margin: "0",
                  paddingBottom: theme.spacing(1),
                }}
              >
                {post.text}
              </p>
            </Card.Content>
            <Card.Footer>
              <div
                css={{
                  display: "flex",
                  gap: theme.spacing(0.5),
                }}
              >
                <Button icon={<ThumbsUp />} label="like"></Button>
                <Button icon={<MessageSquare />} label="Comment"></Button>
                <Button icon={<Share />} label="Share"></Button>
                <Button icon={<Send />} label="Send"></Button>
              </div>
            </Card.Footer>
          </Card>
        ))}
      </main>
    </HomeLayout>
  );
};

export default Home;
