import type { InferGetServerSidePropsType, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Avatar } from "../components/Avatar";
import { Card } from "../components/Card";
import styles from "../styles/Home.module.css";
import { PostData } from "../types";

export const getServerSideProps = async () => {
  // Fetch data from external API
  const res = await fetch(`http://localhost:3000/api/posts`);
  const data: PostData[] = await res.json();

  // Pass data to the page via props
  return { props: { data } };
};

type Props = InferGetServerSidePropsType<typeof getServerSideProps>;

const Home: NextPage<Props> = ({ data }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={styles.main}
        css={(theme) => ({
          maxWidth: 500,
          margin: "0 auto",
          marginTop: theme.spacing(2),
        })}
      >
        <Card>{data[0].text /* <Card.Header></Card.Header> */}</Card>
        <Card>Lol</Card>
      </main>
    </>
  );
};

export default Home;
